#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Dec 12, 2019 04:33:55 AM CST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 9"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set desc "-family {Liberation Sans} -size 9 -weight bold"
set vTcl(actual_gui_font_treeview_desc) $desc
set vTcl(actual_gui_font_treeview_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -background $vTcl(actual_gui_bg) -command on_btnExit \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but43" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -background $vTcl(actual_gui_bg) -borderwidth 3 \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief ridge \
        -text {This is a static label.} 
    vTcl:DefineAlias "$top.lab44" "lblStatic" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 205 -width 355 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    radiobutton $site_3_0.rad46 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Radio 1} -value 1 
    vTcl:DefineAlias "$site_3_0.rad46" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad47 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Radio 2} -value 2 
    vTcl:DefineAlias "$site_3_0.rad47" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad48 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Radio 3} -value 3 
    vTcl:DefineAlias "$site_3_0.rad48" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che49 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text CheckBox -variable che49 
    vTcl:DefineAlias "$site_3_0.che49" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -anchor w -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {This is a dynamic label.} 
    vTcl:DefineAlias "$site_3_0.lab50" "lblDynamic" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.rad46 \
        -in $site_3_0 -x 30 -y 30 -width 89 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad47 \
        -in $site_3_0 -x 30 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 30 -y 90 -width 92 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che49 \
        -in $site_3_0 -x 190 -y 50 -width 103 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 20 -y 150 -width 306 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 440 -y 30 -width 107 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 130 -y 110 -width 186 -relwidth 0 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 80 -y 190 -width 355 -relwidth 0 -height 205 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

